### ISSUE TITLE
Set up notifications so Pingping is aware when the server goes down earlier

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#151] opened 2024-04-11 17:02 UTC
The alarming main script (which is sent to me on an hourly basis) is here (If @ian-r-rose can give me some guidance on the folder structure, I can check in to the specific folder.)

The escalate alert sent to you and Zhenyu is in another script, and it won't be such detailed. 

  

```
#!/bin/bash

RANDOM_STRING=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10)
TMP_FILE=/tmp/monitor_$RANDOM_STRING.txt

machines=("svgcmdl03:2181" "svgcmdl03:9092"  "svgcmdl04:2181" "svgcmdl04:9092" "svgcmdl05:2181" "svgcmdl05:9092" "svgcmdl02:9200" "svgcmdl04:8092" )
echo "Service Status Report" | tee -a $TMP_FILE
echo "-- Background of the report --" | tee -a $TMP_FILE
echo "* The purpose of this report is to monitor the Data Relay server for PEMS modernization project" | tee -a $TMP_FILE
echo "* This report was run at the time $(date '+%a %b %d %H%M%S %Z %Y')" | tee -a $TMP_FILE
echo "* The report is generated from svgcmdl02 machine on etc launch_service_monitor.sh" | tee -a $TMP_FILE
echo "* The owner is pingping.xiu@DOT.ca.gov at BIA team in Traffic Operation, Caltrans" | tee -a $TMP_FILE
echo  | tee -a $TMP_FILE
echo "-- Streaming / Registry Service Status --"  | tee -a $TMP_FILE
healthy_count=0
for machine in "${machines[@]}"; do
    # split IP and port
      IFS=':' read ip port <<< "${machine}"
  # check if telnet connection is successful
  output=$(echo quit | telnet ${ip} ${port} 2>&1)
  if [[ "${output}" = *Escape* ]]; then
    echo "Core Service running at ${ip} ${port} is healthy."  | tee -a $TMP_FILE
    ((healthy_count++))
  else
    echo "Failed to connect to ${ip} on port ${port}"  | tee -a $TMP_FILE
  fi
done


output=$(ssh jupyter@svgcmdl01 'ps -ef | grep oracle_puller_daemon.py | grep python3 | grep -v grep')
if [[ $output == *"jupyter"* ]]; then
    ORACLE_PULLER="healthy"
    ((healthy_count++))
else
    ORACLE_PULLER="UNHEALTHY"
fi
echo ""  | tee -a $TMP_FILE

echo "-- Runner Status --"  | tee -a $TMP_FILE
echo "ORACLE_PULLER running on svgcmdl01 is $ORACLE_PULLER" | tee -a $TMP_FILE

latest_timestamp=$(tail -n1 /tmp/append_to_crawl_queue.log | cut -d' ' -f1,2 | cut -c 1-16)
latest_timestamp_fixed=$(echo "$latest_timestamp" | sed 's/T/ /')
current_time=$(date +"%Y-%m-%d %H")
current_time_seconds=$(date -d "$current_time" +%s)
latest_time_seconds=$(date -d "$latest_timestamp_fixed" +%s)
time_diff=$(( (current_time_seconds - latest_time_seconds) / 3600 ))
echo $time_diff
# Check if the time difference is more than 8 hours
if [ $time_diff -gt 8 ]; then
    TASK_GENERATOR="UNHEALTHY"
else
    TASK_GENERATOR="healthy"
    ((healthy_count++))
fi
echo "TASK_GENERATOR running on svgcmdl02 (under s159123) is $TASK_GENERATOR" | tee -a $TMP_FILE

latest_timestamp=$(tail -n1 /tmp/transporter.log | cut -d' ' -f1,2 | cut -c 1-16)
latest_timestamp_fixed=$(echo "$latest_timestamp" | sed 's/T/ /')
current_time=$(date +"%Y-%m-%d %H")
current_time_seconds=$(date -d "$current_time" +%s)
latest_time_seconds=$(date -d "$latest_timestamp_fixed" +%s)
time_diff=$(( (current_time_seconds - latest_time_seconds) / 3600 ))
echo $time_diff
# Check if the time difference is more than 12 hours
if [ $time_diff -gt 12 ]; then
    AWS_UPLOADER="UNHEALTHY"
else
    AWS_UPLOADER="healthy"
    ((healthy_count++))
fi
echo "AWS_UPLOADER running on svgcmdl02 (under s159123) is $AWS_UPLOADER" | tee -a $TMP_FILE


echo ""  | tee -a $TMP_FILE

echo "-- Overall Relay Service Status --"  | tee -a $TMP_FILE
echo $healthy_count

if [ $healthy_count -lt 11 ]; then
    echo "RELAY" | sed  "s/RELAY/Relay Status UNHEALTHY at $(date) (\x1B[1;31mRED\x1B[0m)/"
    echo "Relay Status UNHEALTHY at $(date)" >> $TMP_FILE
    subject="Relay_Status_UNHEALTHY"
else
    echo ""  | tee -a $TMP_FILE
    echo "RELAY" | sed  "s/RELAY/Relay Status healthy at $(date) (\x1B[1;32mGREEN\x1B[0m)/"
    echo "Relay Status healthy at $(date)" >> $TMP_FILE
    subject="Relay_Status_healthy"
fi

echo ""  | tee -a $TMP_FILE




cat $TMP_FILE | mail -s $subject pingping.xiu@DOT.ca.gov

cat $TMP_FILE >> /var/log/relay_monitor/$(date +"%Y%m%d").txt



```

Output: 
```
Service Status Report
-- Background of the report --
* The purpose of this report is to monitor the Data Relay server for PEMS modernization project
* This report was run at the time Tue Apr 16 164728 PDT 2024
* The report is generated from svgcmdl02 machine on etc launch_service_monitor.sh
* The owner is [pingping.xiu@DOT.ca.gov](mailto:pingping.xiu@DOT.ca.gov) at BIA team in Traffic Operation, Caltrans

-- Streaming / Registry Service Status -- 
Core Service running at svgcmdl03 2181 is healthy.
Core Service running at svgcmdl03 9092 is healthy.
Core Service running at svgcmdl04 2181 is healthy.
Core Service running at svgcmdl04 9092 is healthy.
Core Service running at svgcmdl05 2181 is healthy.
Core Service running at svgcmdl05 9092 is healthy.
Core Service running at svgcmdl02 9200 is healthy.
Core Service running at svgcmdl04 8092 is healthy.

-- Runner Status --
* ORACLE_PULLER running on svgcmdl01 is healthy 
* TASK_GENERATOR running on svgcmdl02 (under s159123) is healthy 
* AWS_UPLOADER running on svgcmdl02 (under s159123) is healthy

-- Overall Relay Service Status --

Relay Status healthy at Tue Apr 16 16:47:28 PDT 2024
```

**Comment by pingpingxiu-DOT-ca-gov** [comment] 2024-04-16 23:36
Today I'm adding alerts for monitoring relay service health. When there is issue, I will get updates and deal with those first. 

@ZhenyuZhu-Caltrans and @ian-r-rose might have received test messages. Moving forward when you see such alarm, the issue is escalated to you if the service disruption is not handled timely.

**Comment by ian-r-rose** [comment] 2024-04-18 15:41
@pingpingxiu-DOT-ca-gov do you consider this issue complete?

**Comment by pingpingxiu-DOT-ca-gov** [comment] 2024-04-18 15:42
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ian-r-rose** [comment] 2024-04-18 15:43
Great, closing now, thanks @pingpingxiu-DOT-ca-gov

**Closed by ian-r-rose** 2024-04-18 15:43 UTC
